# ------------------------------------------------------------------------------
#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
#                           Website: https://vector.dev
#                          Docs: https://vector.dev/docs
#                          Chat: https://chat.vector.dev
#                               VRL: https://vrl.dev
#
# ------------------------------------------------------------------------------
data_dir = "/mnt/data_ext/var"  # Default: /var/lib/vector

# Vector's GraphQL API
#   Enable to try it out with the `vector top` command or http://localhost:8686/playground
[api]
enabled = true
address = "127.0.0.1:8686"

[sources.vector_logs_internal]
type = "internal_logs"

[transforms.vector_logs]
type = "remap"
inputs = ["vector_logs_internal"]
drop_on_error = false
drop_on_abort = false
source = '''
.program = "vector"
.service = "logger"
.host    = get_hostname!()
if exists(.metadata.level) {
  .level = .metadata.level
  del(.metadata.level)
}
'''

[sources.vector_metrics]
type = "internal_metrics"
scrape_interval_secs = 2

[sources.host_cronjobs]
type = "file"
include = ["/var/log/cronjobs.log"]

[sources.host_metrics]
type = "host_metrics"
