[[tests]]
name = "firewall_remap"

  [[tests.inputs]]
    insert_at = "firewall_remap"
    type = "raw"
    value = "[2364744.945059] IN=eth8 OUT=br8 MAC=11:11:11:11:11:11:22:22:22:22:22:22:08:00 SRC=172.64.36.1 DST=192.168.8.60 LEN=91 TOS=0x00 PREC=0x20 TTL=59 ID=593 DF PROTO=UDP SPT=53 DPT=37869 LEN=71"
  [[tests.outputs]]
    extract_from = "firewall_remap"
  [[tests.outputs.conditions]]
    type = "vrl"
    source = """
    .df        == "true"
    .dst.ip    == "192.168.8.60"
    .dst.port  == "37869"
    .id        == "593"
    .len       == "71"
    .prec      == "0x20"
    .ethertype == "IPv4"
    .program   == "nftables"
    .proto     == "udp"
    .service   == "firewall"
    .src.ip    == "172.64.36.1"
    .src.port  == "53"
    .tos       == "0x00"
    .ttl       == "59"
    """

  [[tests.inputs]]
    insert_at = "firewall_remap"
    type = "raw"
    value = "[2366421.766383] IN=br70 OUT= MAC=11:11:11:11:11:11:22:22:22:22:22:22:08:00 SRC=192.168.70.12 DST=192.168.0.1 LEN=116 TOS=0x0A PREC=0x40 TTL=64 ID=0 DF PROTO=TCP SPT=51459 DPT=22 WINDOW=2048 RES=0x00 ACK PSH URGP=0"
  [[tests.outputs]]
    extract_from = "firewall_remap"
  [[tests.outputs.conditions]]
    type = "vrl"
    source = '''
    .df       == "true"
    .dst.ip   == "192.168.0.1"
    .dst.port == "22"
    .id       == "0"
    .in       == "br70"
    .ethertype== "IPv4"
    .out      == ""
    .len      == "116"
    .prec     == "0x40"
    .program  == "nftables"
    .proto    == "tcp"
    .service  == "firewall"
    .src.ip   == "192.168.70.12"
    .src.port == "51459"
    .tos      == "0x0a"
    .ttl      == "64"
    '''
